# -*- coding: utf-8 -*-
"""Spammail_NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_Uop-mRBm37X2E__GXk9mrSdN24moGc
"""

import numpy as np
import pandas as pd
import nltk
df_train=pd.read_csv("/content/SMS_train (1).csv",encoding='ISO-8859-1')
df_train

df_test=pd.read_csv("/content/SMS_test (2).csv",encoding='ISO-8859-1')
df_test

#concatenate
df = pd.concat([df_train, df_test], axis=0, join='inner')
df

df.isna().sum()

df.columns

df.dtypes

df.describe

df['Label']=df['Label'].map({'Spam':1,'Non-Spam':0})
df

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

mail=df.Message_body
mail